### ISSUE TITLE
Dependency issues IntelliJ

### ISSUE THREAD

**Issue by romain77150** [nirrek/bodyTracker#1]
@nirrek i moved to IntelliJ (yeah!) but i still have dependencies issues in renderer.java with 
import gnu.io.CommPort;
import gnu.io.CommPortIdentifier;
import gnu.io.PortInUseException;
import gnu.io.SerialPort;
import gnu.io.SerialPortEvent;
import gnu.io.SerialPortEventListener;

IntelliJ is telling me "cannot resolve symbol CommPort" (compile error) 
Lisa got it working (on Eclipse) by copying the libraries librxtxSerial-2.jnilib (native) and RXTXcomm.jar in /Library/Java/Extension
Is it working fine for you? (i pulled the latest version of the repo)

**Comment by nirrek** [comment]
Project builds fine.

My guess is you are not using Gradle to build the project (instead trying to use Intellij's build tool). You should be performing all tasks using the Gradle build tool. This includes building the project, running the tests, etc.

**Comment by nirrek** [comment]
If you update the Gradle build configuration (eg adding new dependencies) then Intellij can be unaware of these changes. A common problem will be that you add new dependencies, but Intellij doesn't realise that there are new dependencies for the project, so when performing static analysis of your code will tell you that a certain package or class in one of those new dependencies does not exist.

If you've changed the build configuration you can force synchronize the changes by hitting the ![](https://www.jetbrains.com/img/webhelp/idea/refresh.png) button in the Gradle tool window.

Note, however, that this doesn't affect the building of the project at all, as Gradle understands what the dependencies are, and can compile everything correctly. The issue will just be with the hints that the IDE will give you, indicating that they think there is an issue with your code.

**Comment by nirrek** [comment]
Here's a quick screencast showing how to force sychronize the gradle config, so that Intellij's static analyzer knows about the dependencies.

http://d.pr/v/1hy7E

**Comment by romain77150** [comment]
Solved it! It was just because i didn't to import the project as a "Gradle project"! so some settings were wrong...

Now i have an other issue, i still get that error when i run bodyTracker "java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path thrown while loading gnu.io.RXTXCommDriver"
I know why, we talked about it the other day i just can't fix it apparently...
I added -DJava.library.path=/Library/Java/Extensions/ to the VM option in the project settings and i added 
- librxtxSerial-2.jnilib
- RXTXcomm.jar 
to /Library/Java/Extensions/ but it doesn't solve anything...
